---
# 데이터베이스 설정
mysql_root_password: "{{ vault_mysql_root_password }}"
cloudstack_db_password: "{{ vault_cloudstack_db_password }}"

mysql_version: "8.0"
mysql_bind_address: "0.0.0.0"

# CloudStack 데이터베이스
cloudstack_databases:
  - cloud
  - cloud_usage

mysql_max_connections: 500
