---
# Management Server 설정
management_server_ip: "{{ ansible_host }}"

# 데이터베이스 연결 정보
db_host: "{{ hostvars[groups['database'][0]]['ansible_host'] }}"
db_port: 3306

# NFS 서버 설정 (직접 입력)
# NFS 서버 설정이 반드시 되어 있어야 CloudStack Secondary Storage를 마운트할 수 있음
nfs_server: "10.10.0.118"  # NFS 서버 IP 주소
# Ex: /export 
nfs_export_path: ""
# Ex: /export/secondary
nfs_secondary_path: "/export/secondary"
# Ex: /export/primary
nfs_primary_path: "/export/primary"

# CloudStack 데이터베이스 비밀번호
# vault로 관리하므로 vault.yml.example 파일 참조
cloudstack_db_password: "{{ vault_cloudstack_db_password }}"
mysql_root_password: "{{ vault_mysql_root_password }}"

# CloudStack UI 설정
cloudstack_management_memory: 4096
cloudstack_management_port: 8080


# Secondary Storage 마운트 설정
secondary_storage_mount_path: "/mnt/secondary"
mount_secondary_storage: true
nfs_mount_options: "defaults"

# SystemVM Template 설정
force_template_install: false
