---

###############
# 이하 수정 금지 #
###############

# Libvirt 설정
libvirt_listen_tcp: true
libvirt_tcp_port: 16509

# iptables FORWARD 정책
configure_iptables_forward: true

# 스토리지
primary_storage_type: nfs

# KVM 호스트 설정
hypervisor_type: "kvm"

# Root SSH 로그인 (CloudStack Management에서 호스트 추가시 필요)
enable_root_ssh: true