---
# Role: management - CloudStack Management Server
dependencies:
  - role: common

galaxy_info:
  author: CloudStack Team
  description: CloudStack Management Server installation
  license: Apache-2.0
  min_ansible_version: "2.9"
