$ANSIBLE_VAULT;1.1;AES256
36613239663065663561313739646666663034396331396262383564383763633234333038313337
3037336264623935663836316666313761343334643733340a323032633330623831353334353934
33326136373838626339323736643764373130383733633839306136303334343664323035303830
6339623865313533650a333066346136343937663632323839323031393130306334363365363361
63343062383330386464386265343561366465303437356161356333326334633431376338666533
64313534363434333639663433393835633932663630663763623866316432373638636461623036
36303765363834366464323734366164383264666262373334343236396535666331326561316537
35383830643635643434346635373130666137636633613533363962626239363230326662313461
39626165646135666365396532653934633361396533666130626333353764333733343862343061
61646465633031616434366137646537373934636431363862343233313232643762393134373030
64366639666363323030626637626139346236396663623639626139373235653466383638653838
38326236336534633532663032363036376262353562343837383963376139656532313165306636
39336538303865383638613132633062643363623162636233316664353863323464356338383761
36353432313333386661313233633837613464363038633639633464626131333265383034336433
66333738653036336633656361656661663961393534303166643265613539626333613466653337
35323033393638313266386130653066346231313365633366613166633434393833376634613436
62393231653632383765356362323865306562613136643631326234343764386137
